### ISSUE TITLE
Could not select using calender when adding worklog.

### ISSUE THREAD

**Issue by StephanMeijer** [shridhar-tl/jira-assistant#101]
<img width="973" alt="Screenshot 2019-10-21 at 15 58 28" src="https://user-images.githubusercontent.com/3169264/67211810-a6213800-f41b-11e9-8e5c-ebdc884eda8c.png">
<img width="513" alt="Screenshot 2019-10-21 at 15 58 25" src="https://user-images.githubusercontent.com/3169264/67211812-a6b9ce80-f41b-11e9-92fe-afa8ecebae20.png">

Button does not activate calendar anymore (0.82)

**Comment by shridhar-tl** [comment]
@StephanMeijer - Thank you for reporting this issue. This issue has been resolved and is available since v0.83 of Jira Assistant. It is already published but it would take around an hour to be available in webstore. Once your version gets updated, this issue would get resolved. You can also manually update your version once it is available in Web Store.

**Comment by StephanMeijer** [comment]
Indeed fixed
