### ISSUE TITLE
Google Drive Read / Change permission ??

### ISSUE THREAD

**Issue by DarkSlice1** [shridhar-tl/jira-assistant#124]
Can i ask why?

![image](https://user-images.githubusercontent.com/8223630/74758858-d49b0c80-526f-11ea-9d94-e4f1fb594781.png)

**Comment by adrian-moisa** [comment]
This access right should be optional. I have lots of sensitive information there. I'm not so happy to open up access to G Drive. Not going to use the extension until this becomes optional. And I'm really pissed of to do this, the extension is great!

**Comment by shridhar-tl** [comment]
@adrian-moisa , @DarkSlice1 - This doesn't really access your GDrive. It access my GDrive where I had shared some json settings file to share messages. As I do not have any server to store and publish messages, I am using my gdrive to share data with everyone.

This message is actually just the site what it tries to access. It cannot access any other GDrive unless you explicitly grant permission to your GDrive and so far such implementation was not their. But in future I may add that functionality to support backup (only upon explicitly granting permission by you). At this point it does not access you GDrive and you are not granting permission to your GDrive in any way.

You can refer to messagesUrl property in following file which is the file in drive I am trying to access: https://github.com/shridhar-tl/jira-assistant/blob/develop/src/_constants.js. Also this is a open source project and so you can review the source code yourself for any security risks

Just to add on, earlier by default, Jira Assistant had permission to access all the sites and you had granted it. Now I had reduced access to only specific sites which makes it explicitly mention some sites. This infact is much more secured for you than how it was earlier as you get to see each and every site it access. This change was done a couple of month back itself. Just now it is asking for the permission because you would have uninstalled and reinstalled it and the permission you granted earlier to access all sites is removed now as you reinstalled it.

Please feel free to let me know for any more queries. If you are satisfied with the details, please close the ticket.

**Comment by adrian-moisa** [comment]
Much appreciated to get an answer so fast! You are one of those rockstar devs!

**Comment by shridhar-tl** [comment]
Assuming your query is clarified, I am closing this issue. Please feel free to get back to me in case of any additional queries.
