### ISSUE TITLE
Incomplete worklog details  Please provide value for all the mandatory fields

### ISSUE THREAD

**Issue by urscon** [shridhar-tl/jira-assistant#137]
Hi,
I'm new to the plugin and its a rocky start but I see a lot of potential for my team.

The reporting seems good, but the logging doesnt seem to work.. 
Is what I do correct?
In the default view I click on the 3 dots next to a task and click "Add Worklog"
I fill the pop up but then this message appears: Incomplete worklog details
Please provide value for all the mandatory fields

What am I missing?

![image](https://user-images.githubusercontent.com/61714112/75721418-a2aa9100-5cd8-11ea-8b5a-636dae667c3d.png)

This was with 0.96 and with 0.97 its the same (chrome)

**Comment by even-m0re** [comment]
Your comment 'test' only has 4 characters, whereas the sanity check (in my tests, I'm only a user) expects 5 characters minimum for comments. I'm not a fan of this requirement, but that's how it is. :)

**Comment by shridhar-tl** [comment]
@urscon  @even-m0re - You have an option to change this behavior from settings page as shown below.

![image](https://user-images.githubusercontent.com/37339683/76682291-d6fb4700-6620-11ea-995f-f86bcc2c8450.png)


You also have an option to log work from calendar module. You can just click and drag from calendar module and create work log which is more convenient to create worklog.

Info: Click on Video help icon from top right corner from any page to see page specific help video. Hope this solves your issue. If your issue is still not resolved then please reopen this issue.
