### ISSUE TITLE
Calendar view - adding new workload eg from 11AM to 02PM does not set properly staring hour/minutes

### ISSUE THREAD

**Issue by SirYasko** [shridhar-tl/jira-assistant#162]
Date is set properly, duration (worktime) also but starting time is set to 12AM instead of 11AM
![image](https://user-images.githubusercontent.com/66648865/89016672-66c43800-d319-11ea-9c36-056784d8f03c.png)

**Comment by OsimonB** [comment]
Selecting from 8.30AM to 9AM
![image](https://user-images.githubusercontent.com/1261461/89579548-12283c00-d888-11ea-8486-896a11921d86.png)

Opens the new worklog window with the Log Time being the start of the calendar day (in my case 7AM)
![image](https://user-images.githubusercontent.com/1261461/89579657-48fe5200-d888-11ea-89ad-96fc95c5f62a.png)

Although interestingly, if you drag any of the panels (even without actually moving them)
![image](https://user-images.githubusercontent.com/1261461/89579748-69c6a780-d888-11ea-881d-b744638897c2.png)

Then it begins to work again as expected:
![image](https://user-images.githubusercontent.com/1261461/89579821-882ca300-d888-11ea-9426-173951fb98b9.png)

It seems like something isn't getting initialized correctly, so this work around is good enough for the time being but would love to see a fix for it

**Comment by SirYasko** [comment]
I can confirm, if you drag panel time is set correctly

**Comment by shridhar-tl** [comment]
Tried to reproduce this issue in chrome and I was unable to reproduce it. This functionality is untouched since very long time and no one else has reported this issue so far. So I think their would be some thing different in your instance / system configuration.

Can you provide answers for following questions which would help me in reproducing this issue.

1. Can you let me know in which browser it is happening?
2. Is it happening only when you add it as gadget in dashboard or it happens in calendar page as well?
3. How are navigating to this page? Directly coming to this page or go to some other page and click on the menu and come to this page?
4. Are their any errors in console?
5. Are their any one else facing this issue you know of? Any other clue or scenario you could think of which is different in your case?

**Comment by OsimonB** [comment]
Hey @shridhar-tl, thanks for getting back to us! This bug has been affecting me over the last few months, but no one else in our team was experiencing the issue.

I think I have managed to replicate the issue consistently on my setup, it only happens when the Calendar page is set to the Month View. Both the Day and Week dashboard panel are affected. **Changing the Calendar page to be viewed by day or week fixes the issue**

1. Google Chrome - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
2. It seems to only happen in the dashboard view (see note above)
3. I navigate directly to the dashboard view
4. No errors are in the console
5. No one else in my team was facing the issue, but we have been able to replicate it since

**Comment by SirYasko** [comment]
1. Google Chrome | 84.0.4147.105 (64-bit) (cohort: Stable),| Windows 10 OS Version 1909 (Build 18363.959)
2. It happens in dashboard, not noticed on Calendar page, and I can confirm @OsimonB info "**Changing the Calendar page to be viewed by day or week fixes the issue"**
3. directly to the dashboard
4. ![image](https://user-images.githubusercontent.com/66648865/89760789-5ff1ae00-daed-11ea-889c-6a856d77c740.png)
5. @shridhar-tl, please try:
- go to Activities Calendar/Worklogs and switch calendar to MONTH view
- back to the dashboard (with calendar panel) and try to log work

**Comment by shridhar-tl** [comment]
Is this still an issue in latest version of JA? Jira Assistant v1.8 should have the fixes. Kindly verify it once and let me know if we are good to close this ticket.

**Comment by OsimonB** [comment]
I can verify that it is no longer an issue @shridhar-tl 👍

**Comment by SirYasko** [comment]
Seems to be OK now. Thanks!
