### ISSUE TITLE
The "Worklog Report" only shows the worklog for the current user

### ISSUE THREAD

**Issue by a2lgols** [shridhar-tl/jira-assistant#169]
Have been using the Jira extension for a while and it works great. However, starting Oct 2, one can only view their own worklog using the out of the box "Worklog Report". You can't see the worklog for other team members.

**Comment by shridhar-tl** [comment]
Are you using cloud version of Jira or self hosted version? You can try to remove the user from user groups once, and add it again and check?

**Comment by a2lgols** [comment]
Thanks for getting back @shridhar-tl 
Deleting the group and recreating it worked. (I am using the cloud version)

**Comment by shridhar-tl** [comment]
@a2lgols - Thank you for confirming. This is due to the updates in Jira cloud where the user id is removed and going forward JQL query works only with email address, which is rolled out for uses in batches and you got this update now. The old profile which you added to group earlier contains user id. Hence with that user id Jira Api doesn't return the data. Now once you clear the old list and add the user again, it started working.
