### ISSUE TITLE
Working hours and days setting has no effect on calendar view

### ISSUE THREAD

**Issue by opiechow** [shridhar-tl/jira-assistant#170]
Jira Assistant v.1.9
On Firefox 78.4.0esr (64-bit):

Setting the settings in General tab:
![image](https://user-images.githubusercontent.com/12622836/97328564-71d62800-1876-11eb-8b9a-205db488af7c.png)

Doesn't affect the view in the Calendar view:
![image](https://user-images.githubusercontent.com/12622836/97328700-929e7d80-1876-11eb-9221-855b5b3ba7e6.png)

Expectation:
Friday would be grayed out in with the settings as on screenshot

**Comment by shridhar-tl** [comment]
@opiechow - Thank you for reporting this issue. Please find below my reply:

1) Working hours you set in screenshot matches with calendars. You set 9AM to 5PM and same is visible in calendar as well. This is the expected behavior and I do not see any issues with it based on your screenshot.

2) Working days: This setting is not applied to calendar so far. I will check the feasibility for this. I mostly think this is not supported by the calendar control I am using and in case if this is not supported, then it would be more effort to implement. I will get back to you on this ASAP.

By the way, you mentioned you are using v1.9 of Jira Assistant. But already v2.3 is published and hence I would suggest you to update to latest version. So far no new issues were reported in v2.3 and hence I would consider that to be the latest stable release.

**Comment by opiechow** [comment]
@shridhar-tl 

1. I see that the working hours affects the general range of displayed hours, but it does not affect the grayed out area. See attached two screenshots with different settings to see what I mean:
Settings:
![image](https://user-images.githubusercontent.com/12622836/97882876-6e361b80-1d24-11eb-95c3-89295a3cf553.png)
Resulting view:
![image](https://user-images.githubusercontent.com/12622836/97882973-8dcd4400-1d24-11eb-8701-26110b700f96.png)
(and I can scroll down until 18:00).
So I would suggest to maybe rename the setting from "working hours" to "displayed hours" then?
2. OK, waiting for feeback :+1: 

I also updated to 2.3, for whatever reason Firefox didn't update it automatically (I think because I might have been installing the self-hosted version).

Also thanks for the fast reply and for maintaining this project, it makes life so much easier :1st_place_medal:

**Comment by shridhar-tl** [comment]
This issue has been resolved in Jira Assist v2.33. You should see it working once updated to the mentioned version. Hence closing this issue.
