### ISSUE TITLE
Can't connect to jira. Reinstall needed.

### ISSUE THREAD

**Issue by drozel** [shridhar-tl/jira-assistant#173]
Hello. First, many thanks for this really handy extension.
I have an issue that forces me to reinstall extension in average 1 time per week.
At some point of time, it tells me that i'm not authorized. When I open my Jira page, it's there. Only extension remove and re-install help.

Today I got this issue again, wen to the Jira page to recheck if I'm authenticated and come back to extension. This time it won't load at all:
![image](https://user-images.githubusercontent.com/6229397/98578544-c8535580-22bd-11eb-91f8-1e561499bfdd.png)

That's something new. Maybe it helps to debug the issue.

**Comment by guilhem-lk** [comment]
Hello, I also have this issue with the same stacktrace in the console. Is there any news on this bug?
Thanks

**Comment by guilhem-lk** [comment]
Hello @shridhar-tl, this bug is really annoying and force me to reinstall the extension sometimes several times per week.

Do you need some information or help to debug it?

**Comment by 57an** [comment]
Have same issue on my work PC, ready to give needed information

**Comment by novosirj** [comment]
I have this issue too. We use CAS for authentication for Jira, if that makes any difference. It seems unrelated to any CAS expiration though, since it often survives this.

Where I end up is the 401/Unauthenticated page, but re-authenticating does not help.

It does seem like our system also may have a shorter timeout in Jira than the timeout in CAS, if that helps track this down at all.

**Comment by shridhar-tl** [comment]
Hi All, I hope this issue would have been resolved as part of #214. If anyone is still facing this issue, please provide additional details as mentioned in the ticket.

Closing this ticket assuming this issue is resolved.
