### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by KirillZinchenko** [shridhar-tl/jira-assistant#176]
Hi,

Currently many of macOS users are starting to use Safari as their main browser (because of Big Sur optimizations, especially  for M1 Macbooks).

Any plans to port Jira Assistant to Safari?

**Comment by Thomas-iMac** [comment]
I would like to re-start the need for a Jira Assistant for Safari.
Many thanks
Thomas-iMac

**Comment by shridhar-tl** [comment]
Hi, I'm a windows user and I do not have any MAC machines. For building package for Safari, it becomes necessary to have a MAC machine with xCode installed.

Hence I would need support from other MAC users to build the package. If someone is ready to volunteer, please contact me through mail. Until then, this issue is blocked and I would not be able to proceed with it.

**Comment by shridhar-tl** [comment]
As I don't see any volunteer's, I am closing this issue for now. Let me look into the feasibility later at some point.
