### ISSUE TITLE
Worklog import incorrectly parses decimal hours

### ISSUE THREAD

**Issue by sundquistm** [shridhar-tl/jira-assistant#185]
I log my time in decimal format (e.g., 12.5 = 12h 30m.) This works fine when I do it through JIRA/Tempo.

With JA's Import Worklog feature, the values seem to get parsed literally.

Example: Using JA's own sample_worklog.csv file (which demonstrates various value formats), a value of "12.5" gets read as "12h 5m" instead of "12h 30m".
Example: A value of "0.1" gets read as "1m" instead of "5m"
Example: A value of "0.11" gets read as "11m" instead of "7m"

I think this could cause fairly severe issues if someone doesn't notice it.

**Comment by DaniilLyzo** [comment]
Same here. 30 minutes is logged in downloaded excel file in Flat Worklogs as 30 h. 
1 h 30 min is logged as 1 hour. 

Sure, it will cause severe issues. Thank you, guys.

**Comment by shridhar-tl** [comment]
@DaniilLyzo @sundquistm - This issue has been resolved and is not available for you to test. Please update your extension if it did not happen automatically and verify if it is working as expected.

**Comment by DaniilLyzo** [comment]
WEB IMAGE  ![image](https://user-images.githubusercontent.com/73445495/118363253-27ab5e80-b59c-11eb-9fc7-d82906ffa2ff.png)
 
EXCEL IMAGE: 
![image](https://user-images.githubusercontent.com/73445495/118363273-3db91f00-b59c-11eb-9591-670e3d8a376f.png)

@shridhar-tl Thank you for your reply. :) Updated to version 2.31. Unfortunately, the Issuer still remains. Check the above-attached screenshots.

**Comment by shridhar-tl** [comment]
Hi @DaniilLyzo , I just realized what the issue was after trying couple of times in past one week. I will try to fix it ASAP, but till then you can do small workaround to fix it.

Go to worklog report and click on Settings icon from top right corner of the page
Change the Log hour format like shown in the following screenshot:
![image](https://user-images.githubusercontent.com/37339683/119763192-b8533a00-becc-11eb-867f-52afccf6d362.png)

Now try to export and you should see it properly. You can use it this way untill you have the issues resolved. Once again thank you for reporting this issue. Please feel free to let me know if you face any other issues.
