### ISSUE TITLE
doesn't connect using Firefox

### ISSUE THREAD

**Issue by giorgiobeggiora** [shridhar-tl/jira-assistant#209]
The extension connects using Chrome, but not using Firefox. Proxy settings are set to "Use system settings" for both of the browsers, and system settings is set to "Auto discovery". The JIRA URL is not under VPN. I tried three different networks.

NETWORK ERROR. Unable to connect to server. Please check your network connectivity.

**Comment by view2killu** [comment]
the same here...

**Comment by shridhar-tl** [comment]
Hi @Silverium - Thank you for your findings. This would be helpful in resolving the issue. I will try to resolve this issue by this weekend.

**Comment by Silverium** [comment]
Moreover, the firefox browser working was a Firefox Developer Edition v101.XXX and the Firefox version NOT working is v103.XXX. (64-bit both)

**Comment by shridhar-tl** [comment]
I hope this issue is resolved already in previous release. Please reopen this ticket if you are still facing this issue.

Additionally, some of the known issues due to invalid input is provided with workaround fix in upcoming version. Additionally improved error messages would help in understanding the error easily.

**Comment by Silverium** [comment]
Yes, thanks. Your swift fix convinced me to donate to the project. Every bit counts :)
