### ISSUE TITLE
When copying issues in different weeks, defaulting the date to today is unexpected

### ISSUE THREAD

**Issue by johnbeard** [shridhar-tl/jira-assistant#212]
When copying issues in the calendar view, the date defaults to today. When looking at older weeks, this often causes the newly-created issue to vanish, as it will move to the current week.

In conjunction with #211, this makes it very easy to fail to correct the date and then the new issue vanishes into a different week.

I suggest that when copying an issue, the date defaults to the date of the copied issue. Then, there could be a quick, explicit, way to move the issue to "today" (for example a button next to the date input, and/or menu entry). Or, a configuration to default copied issues to "today" if that's an important and intentional workflow feature for some users.

**Comment by shridhar-tl** [comment]
Hi @johnbeard Thank you for your suggestion. But this feature was implemented so based on feedbacks given my multiple users earlier and based on data I have, most of the users copy worklog to create it for current day and hence this suggestion would make it unobvious for those users.

The alternate option you suggested is still an additional activity those users will have to do and moreover for all the users who got used with this functionality, this change would cause difficulties.

Hence as of now this functionality would be un touched and if their are more popularity for this issue, this would be considered.

**Comment by shridhar-tl** [comment]
Hi @johnbeard - Now in latest version of Jira Assistant v2.44, you have clone option as well which is just a click of icon in each entry in calendar. That would create new entry in same date and time which can me moved by user to any other day. So that should solve your usecase as well by using this clone feature instead of existing Copy feature.

Closing this issue considering your issue would be solved by this new feature.
