### ISSUE TITLE
Worklog Calendar cannot drag and drop logged time between days

### ISSUE THREAD

**Issue by twinklefingers** [shridhar-tl/jira-assistant#217]
**Basic Details**
- What is the version of Jira Assistant you are using? v2.37
- Browser & Version? Chrome Version 103.0.5060.66 (Official Build) (64-bit)
- What OS are you using? : [e.g. iOS, Windows] (not necessary for all issues) Windows

**Describe the bug**
Before the UI update, I frequently used the feature of drag and drop our logged time between calendar days on the  Worklog Calendar.  Now I receive the error: 
Unhandled error
An unknown error occured while processing your request

It is a pop up in red in the upper right corner of the screen.

**To Reproduce**
Steps to reproduce the behavior (if applicable / necessary):
1. Go to Worklog Calendar
2. Click on a row of logged time, begins with a dot and a timestamp followed by JIRA ID
3. Try to drag to another calendar day
4. See error in top right

**Expected behavior**
Drag and drop into a new day should update the date of the JIRA task logged time

**Comment by shridhar-tl** [comment]
@twinklefingers - I was not able to reproduce this issue. When this issue happens, can you take the screenshot of the console error and send it. That would contain more technical details on what is exactly causing this error.

**Comment by twinklefingers** [comment]
![JA error](https://user-images.githubusercontent.com/19318627/178070299-082b205f-1d55-4de5-89bb-9722aec15548.PNG)

**Comment by shridhar-tl** [comment]
@twinklefingers - Thank you for your screenshot. Earlier with your description I was not able to understand the fact that, this issue is happening in Month View. I tried to reproduce this issue in Week view with various scenarios and I was not able to reproduce it. But this screenshot gave a quick understanding on what is causing this issue and was able to resolve it.

This fix would be available once v2.38 is published and I expect it would be available within a week's time.

**Comment by shridhar-tl** [comment]
This fix is already available in Jira Assistant v2.38 published couple of days back. You can update to that version to get the issue resolved.
