### ISSUE TITLE
Visual overlap of one record on top of the other despite the fact that there is a gap of 1 minute between them

### ISSUE THREAD

**Issue by Kudrat89** [shridhar-tl/jira-assistant#218]
The records were made only in Jire
![image](https://user-images.githubusercontent.com/101562683/177982813-859db1e1-365f-469a-9174-5179705f9ee6.png)

The first entry was made in 1:53 pm - 2:02 pm
![image](https://user-images.githubusercontent.com/101562683/177980226-4d9b617a-d5a8-4def-895b-3ffffc445bb7.png)
The second entry was made in 2:03 - 2:08

I am adding a screenshot which shows that I encounter this problem very often
![image](https://user-images.githubusercontent.com/101562683/177981224-1cbfd4eb-476e-4000-9be1-ec84eb97a7c7.png)

**Comment by shridhar-tl** [comment]
@Kudrat89 - This visual overlap happens only when worklog is lesser than 10 minutes. That is because of the fact that lesser than 10 minutes makes it too small and hence some minimum height is being set so that users would be able to resize or click on it. Having it even smaller would make it very difficult for the uses to interact with it. As this would be an edge case and a hard UI issue to provide a fix, I'm closing this issue for now. Later if I could find a feasible solution, I will try to fix this issue.
