### ISSUE TITLE
Save or Export Settings and reimport

### ISSUE THREAD

**Issue by MaeChr** [shridhar-tl/jira-assistant#227]
It would be helpfull to Save or better Export the Settings of a dashboard including all settings like indivdual reports, work log and so on.
And latter import it to an another browser or the same. eg. after a new installation of PC or browser

**Comment by shridhar-tl** [comment]
Hi @MaeChr, This is already an existing feature in Jira Assistant. Additionally to import the settings import option is provided in integrate page as well. Please update to latest version (i.e. v2.41) of Jira Assistant if you do not see it. You can also use it from Web Version of JA by accessing https://app.jiraassistant.com.

![image](https://user-images.githubusercontent.com/37339683/187833047-61f9b64c-4ced-45d6-8e35-cbea94ad8272.png)

Though notifications are provided about updates, most of the user do not keep track of the updates available. I would request you to keep track of the updates so that you may miss out new features. Their has been multiple new features / updates in Jira Assistant since past few months, hidden behind some settings and I have been actively working on new features.

As this is an existing feature closing this issue considering it is resolved. If you find any bugs or if you are looking for more enhancements, please feel free to reopen or add comments regarding the same.
