### ISSUE TITLE
Epics are not shown neither in the new nor in the old worklog report

### ISSUE THREAD

**Issue by Ernte1893** [shridhar-tl/jira-assistant#250]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.44

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

When enabling the optional option in the worklog report to also show the epic field, the epic column is shown, but remains empty. All tickets are shown, but the epic connection is not visible.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @Ernte1893 - This is partially a known issue. In General Settings -> Default value tab, you have a field where you need to select Epic name field. Once you navigate there it would auto select Epic Link as the value. You can change the field to be used (if required), then you can once again navigate back to report and you will see the Epic link value is populated in both the report. By default epic link should be the correct field, however in some instance of Jira it is customized and that is the reason it is necessary for the user to change it from this page.

![image](https://user-images.githubusercontent.com/37339683/210296378-aa7038c1-adc2-493b-851e-56223c49dd5e.png)

However, I just realized that this field is not being populated in New Worklog Report, while using timeframe as sprint. This would be fixed in upcoming release in couple of week.

**Comment by shridhar-tl** [comment]
This issue has been fixed and would be available in JA v2.45 once published. It would immediately be available in web version.

Closing this ticket considering this issue is resolved.
