### ISSUE TITLE
Summary tab is missing in the New Worklog report

### ISSUE THREAD

**Issue by SelvalakshmiPraveen** [shridhar-tl/jira-assistant#260]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.44

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

Summary section is not available in New Worklog Report. Summary was really helpful to get the Total hours both Resource wise and Project Wise.

Old Worklog :

<img width="837" alt="image" src="https://user-images.githubusercontent.com/78785914/211570728-16ff0ec5-2851-4240-b551-00d5e50f6272.png">

New Worklog : 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/78785914/211570938-ed2a9e31-328c-4f0a-ad39-e493656b5ca7.png">

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @SelvalakshmiPraveen - I intentionally did not add it to new worklog report because there are more option to group the worklogs based on project, epic, issuetype, etc which implicitly gives the details which was available in Summary tab. So I do not see the need to have that tab separately.

To enable custom grouping open Report Configurations from top right corner and look at the Datasource tab for "User worklog grouping" as shown in following screenshot. If you still see any need for Summary tab, please let me know what is that you like over there and I will think through it.

![image](https://user-images.githubusercontent.com/37339683/211582078-9f0e58a9-14e6-4d71-ab83-7d3b0b4765c3.png)

Until you get back, I assume the option is already available in different place and hence closing this ticket. Please reopen with your comments as necessary.

**Comment by SelvalakshmiPraveen** [comment]
Shridhar,

Thanks for your quick response. I see the grouping options are given already. But Summary Tab is unique and was very helpful. It gives us the insights about the total worklog of user as well as the Project in one single view in horizontal and vertical ways.

In grouping option, for example if I group by Project, I will get a worklog Project wise only. If I need to check for one user, I need to again switch the grouping. In Summary tab, As everything was in single wise, it helps us to create a report and submit it to our Management. 

Grouped Option :

<img width="841" alt="image" src="https://user-images.githubusercontent.com/78785914/211597771-3b9a448d-943a-4f68-b8e8-1b66e7d22a70.png">

Worklog Option (Here it more readable as it is horizontal and vertical manner) :

<img width="839" alt="image" src="https://user-images.githubusercontent.com/78785914/211599167-3f940829-4ade-4f5d-b28b-769fbabab66c.png">


Also, the old worklog will get removed and it will be there always?
