### ISSUE TITLE
Add "hour lines" to calendar when using it in dark mode

### ISSUE THREAD

**Issue by taboo180** [shridhar-tl/jira-assistant#267]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Firefox

### Feature Suggestion

When using the calendar in light mode each hour/half hour has a horizontal line that helps break up the day. When using the calendar in dark mode the lines don't exist making the whole calendar look like a single dark blog with little separation.

Light mode:
![image](https://user-images.githubusercontent.com/47477508/212612569-c517baba-e61a-4cbf-abf6-2172ae87a875.png)

Dark mode:
![image](https://user-images.githubusercontent.com/47477508/212612606-17e2c489-de83-4e40-8d33-34cf34794209.png)

Thanks.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
@taboo180 - Thank you for reporting this issue. While I see it working as expected in other browsers as shown in following screenshot, I did not realize it is broken in Firefox. I will try to have it fixed in v2.48 for extension. As you are using Web version, you should start seeing it as soon as it is fixed.

![image](https://user-images.githubusercontent.com/37339683/212791686-d2448fc2-a769-41fe-ac8c-50338a488b18.png)

I additionally realized the text inside the event is going out of the grid based on your screenshot. Will try to fix that as well along with this issue.

**Comment by taboo180** [comment]
Perfect =), thanks for giving it your attention.

**Comment by shridhar-tl** [comment]
@taboo180 - This issue has been resolved and is already published for Web version of JA. Fixes would be available for extensions in v2.48 which would be published in next couple of weeks.

Closing this issue as it is fixed. You can test it in Web and reopen it if you still face any other issue.
