### ISSUE TITLE
When Clicking on own name in User Groups , new page with JSON output appears. 

### ISSUE THREAD

**Issue by GregoryMachin** [shridhar-tl/jira-assistant#268]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

v2.44

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

The plugin available for Edge is not the latest version from what I can see.

![image](https://user-images.githubusercontent.com/29277026/212774651-f9365d42-5797-4189-a400-b7ce888b94a1.png)

My installed version is the same as that provided via the Edge extensions store. 

The real issue:

When clicking on my account name under the User Groups :

![image](https://user-images.githubusercontent.com/29277026/212774078-cc6cd87f-bd7b-475c-b496-1d272eafd1b5.png)

A new page opens with json output. I'm not pasting this output here because it likely to contain sensitive info. 

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @GregoryMachin,
Thank you for reporting this issue. This issue has been fixed and would be available in Jira Assistant v2.48. Once you have your extension updated to mentioned version, you will start seeing this fix. However you will be able to verify the fix in next couple of hours  from Web version by accessing https://app.jiraassistant.com in next couple 

And about your extension staying on v2.44, yes, this is known case. I did not publish couple of versions to Edge as those versions had known issue and I wanted to avoid it affecting all the users. However v2.47 is already published to Edge and is currently being reviewed by Web Store team. Once their review is done and approved, all the users will start getting those updates which I expect to happen within this week.

Considering this issue is resolved, I am closing this ticket. Please feel free to reopen it if you see any issue in future.
