### ISSUE TITLE
Dark Mode: Ticket no overview incorrect color, not readable

### ISSUE THREAD

**Issue by SSeltonrijch** [shridhar-tl/jira-assistant#276]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

V2.44

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

In the add worklog window, you can fill in your Jira ticket nr. When you start typing it will show the corresponding ticket numbers in a drop down menu.

In Dark mode the text is not readable. I did not check it for the over modes, but for Dark mode it is a problem. See below printscreen.
![image](https://user-images.githubusercontent.com/124683961/217241083-9c7aa03d-7062-4c98-9a1a-2e9bdb49484b.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @SSeltonrijch - Thank you for reporting this issue. However this issue has been resolved long back and you are using very old version of Jira Assistant. Current version of Jira Assistant is v2.47 and I do not see any issue with it. Look at the screenshot below with latest version:

![image](https://user-images.githubusercontent.com/37339683/217419823-cf0829b9-fc57-4943-8b52-4f1f89793d2b.png)

Kindly update your version of Jira Assistant and you should see the issue resolved. To update your extension, navigate to "chrome://extension", then enable Dev mode from top right corner and then click Update extension button from top left corner. In next few seconds your extension should get updated and you will have this issue resolved.

Hoping this comment helps, I am closing this ticket. Please feel free to reopen if your issue is still not resolved.
