### ISSUE TITLE
Worklog report saving for future use, need 2 reports for 2 different teams

### ISSUE THREAD

**Issue by sunilthota20** [shridhar-tl/jira-assistant#278]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

Web

### What browser are you using?

Chrome

### Feature Suggestion

Hi Team,
i need to run work log report for 2 different group of resources,
everytime i need to update query to filter and run report,
checking on possibility to save this as different reports so that i can just run with a click and no need to update query every time
please suggest

thanks in advance

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by shridhar-tl** [comment]
Hi @sunilthota20 , I have partially done the implementation to support adding worklog report as a gadget to dashboard. While I have already implemented it for Jira Cloud app, next step is to implement the same for Extension and Web as well.

This would be available in Jira Assistant v2.48 by end of this month. Once this is available, you can create multiple dashboard, configure and add this report in each dashboard as gadget. Each gadget you add would have isolated configuration and so that would solve your issue.

If you have any better suggestion, of if you feel this option does not work well, please feel free to provide your feedback.

**Comment by shridhar-tl** [comment]
Hi @sunilthota20  - I have provided support to add Worklog report as gadget to any dashboards. That way, you can add it as gadget to dashboard and configure it individually to view report for different teams. While this change is already available in Web version of JA, it would be published for extension users by the end of this month and would be available once your extension gets updated to v2.48.

Closing this ticket hoping this solves your issue. Please feel free to reopen this ticket if you see any other issue.
