### ISSUE TITLE
Worklog Report Export file (xls) is corrupt

### ISSUE THREAD

**Issue by toebgen** [shridhar-tl/jira-assistant#282]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Build: 19-Feb-2023 04:54:17 PM (Web)

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

MAC OS

### Bug Description

First of all, thanks for the great tool! :)

I experienced the following bug recently. After performing the steps/clicks: 

Worklog Report > This Month > Export to Excel

I cannot open the xls file with MS Excel, receiving the following error messages:

![Screenshot_1](https://user-images.githubusercontent.com/1238253/220636241-aec1b725-765b-437c-95cb-d0eff35e058c.png)
![Screenshot_2](https://user-images.githubusercontent.com/1238253/220636277-e00f2b81-372e-419c-b12e-23d66ed4a39b.png)

I am happy to provide any further details if needed.

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@toebgen - Thank you for reporting this issue. Some of the users like you using Web version is really helping me to identify the issues much quicker before I publish the updates for extension users.

Once updates are published for extension, the time to resolve this issue is very huge due to Web Store review process.

Now this issue is resolved and in next few minutes, you would be able to see in updates in Web version.

Considering this issue is resolved, closing this ticket. Please feel free to re-open it, if you face any other issues.
