### ISSUE TITLE
Import worklog doesn't work

### ISSUE THREAD

**Issue by kihayu** [shridhar-tl/jira-assistant#290]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

MAC OS

### Bug Description

I tried to import my worklog today and noticed that nothing got imported. The console threw the following error:
```
Uncaught TypeError: e.replace is not a function
    at Object.transformHeader (290.c208ff31.chunk.js:1:665)
    at g.parse (997.d9a5e47f.chunk.js:2:15721)
    at c.parse (997.d9a5e47f.chunk.js:2:14506)
    at f.parseChunk (997.d9a5e47f.chunk.js:2:6148)
    at f._chunkLoaded (997.d9a5e47f.chunk.js:2:9548)
    at FileReader.<anonymous> (997.d9a5e47f.chunk.js:2:18643)
```

After some digging, I figured out that the loop that iterates through the headers (of the CSV file) and formats them also tries to format a function called "init" which leads to the crash.
The line where the crash happens is https://github.com/shridhar-tl/jira-assistant/blob/master/src/views/bulk-import/worklog/ImportWorklog.js#L64

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by Dannen11** [comment]
Same issue with me:

![image](https://github.com/shridhar-tl/jira-assistant/assets/134703907/3db3188b-b5c0-4efd-b475-72ce246b1689)

How do you use Jira Assistant?
Web version and tried it with jira cloud plugin

Are you using cloud version of Jira or self hosted (data center / server) of Jira.
Cloud Jira

Version of Jira Assistant
Web, Jira Cloud Plugin

What browser are you using?
Chrome

What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.
Win11

Bug Description
I could import worklog to jira cloud till February by Jira Cloud plugin. I tried it yesterday again and got the error message "Unhandled error
An unknown error occured while processing your request"
After this I deinstalled the plugin and used Jira Assistent as Chrome web app -> same error. It doesn't matter which cvs file I use.

**Comment by TomyLobo** [comment]
This stopped working for me when upgrading for 2.48 to 2.49 as well.
Downgraded to 2.48 and it worked again.
Kubuntu 18.04
Firefox 113.0.1 (64-bit)
I'm using the regular add-on for firefox.

**Comment by shridhar-tl** [comment]
@TomyLobo - Thank you for letting me know about the issue. I will have a look at it on priority basis.

But the old issue being reported in this ticket is not being reproducible. Till v2.48, I have tried it and it was working fine. Any way, will look into it today and get back to you.

**Comment by shridhar-tl** [comment]
Hi @TomyLobo - This issue has been resolved and now I was able to import worklog. This was due to one of the library which I was using. I upgraded to latest version and something has broken. I have resolved it now and you should see it working once I publish JA v2.51.

However it is already published to Web version and you can temporarily switch to Web version and try it out.

By the way, you will receive updates in Web version much quicker than any other options. Also it would be helpful for me to know about any issues well in advance before I publish the changes to extension.

**Comment by TomyLobo** [comment]
thank you for resolving this so quickly :)
I need to use the browser extension since this is an internal instance and I can't share my login credentials with your web site anyway.
But since I was able to downgrade without issue (and I'm on vacation for this week anyway), waiting for the release is not a problem :)

**Comment by shridhar-tl** [comment]
@TomyLobo - Sure as you wish. However I would like to clarify one thing thought:

To use web version, you need not share the credentials in web version. That web version is just going to use the latest code for display purpose, otherwise, still extension is going to take care of pulling the data.

So if you want to switch to web version, it would happen seamlessly without having to provide the credentials. All your data would stay in extensions internal storage only. Website will not store any of your data in any form. It would just display the data using latest code.

Just to give you more technical information, this website does not even have a backend server. It is just a static website hosted on github itself in this same repository.
