### ISSUE TITLE
Calendar view overlap of entries

### ISSUE THREAD

**Issue by jazzlyn** [shridhar-tl/jira-assistant#292]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

web

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Linux

### Bug Description

unfortunately, calendar entries are now overlapping - see screenshot
new entries are set to have 15 min default but it preselects 30 min.
checked the general settings, worklog default timespent is set to 00:15.

![JA-calendar-overlap](https://user-images.githubusercontent.com/9011011/226566829-9793b4cd-4362-431e-ac19-85a6a2f9bbed.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@jazzlyn - This issue is due to the enhancement done as part of #289 as small events are not visible. While some users feel its ok to overlap when the events are small so that its readable, others feel overlapping is not good. I couldn't find a way to achieve both. So I moved the changes related to #289 behind the configuration.

So the issue you reported is resolved as part of this fix. Hence closing this ticket. Please feel free to reopen it if you face any other issue.
