### ISSUE TITLE
Adjust Remaining time when creating work log

### ISSUE THREAD

**Issue by vidgeus** [shridhar-tl/jira-assistant#293]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that there are no existing requests with similar suggestion in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

2.48

### What browser are you using?

Chrome

### Feature Suggestion

**Context**
When I log time via Work Log Jira feature I always adjust the remaining time. In this way I know how well I am doing in the Sprint. 
So I log time spent and also adjust remaining time.

**Request**
Please add ability to adjust Remaining Time via JA.
![image](https://user-images.githubusercontent.com/13273119/228275182-07955141-06de-4f60-a4af-aefa910fc3cd.png)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have added required screenshots (as necessary)

**Comment by davidpurdue** [comment]
I just came here to lodge this exact enhancement request.

**Comment by shridhar-tl** [comment]
Hi @vidgeus @davidpurdue  - This implementation is done and it would be available for extension users once your extension gets updated to v2.49. However, it is already available in Web version. For tie being you can switch to web version and use / test it.

Here is the snapshot of how the add worklog popup appear after this implementation.

![image](https://github.com/shridhar-tl/jira-assistant/assets/37339683/89ef6ac6-feab-4693-ad5d-d356c3459f4e)

I will wait for one more week so that I can test it properly before publishing the extension. You can also try to use it from web version and let me know if you face any issues.

Closing this ticket assuming requested implementation is done. Please feel free to reopen this ticket if you face any issue.
