### ISSUE TITLE
One issue don´t show logs/records in worklog calendar

### ISSUE THREAD

**Issue by frgopplus** [shridhar-tl/jira-assistant#295]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

9.4.1

### What browser are you using?

Firefox

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

At worklog calendar, i can view all logs from different issues except one. This issue have at this time 2322 worklogs in database (SQL Server).
The gap in calendar is empty for logs from this issue.

![jira assistan issue 2](https://user-images.githubusercontent.com/132886855/236775890-2ff8c91b-54ce-4e9e-a0f6-5640dd03bcea.JPG)
![jira assistan issue](https://user-images.githubusercontent.com/132886855/236775898-b291ddc1-007b-41e7-84a9-a7a88ad78214.JPG)

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
@frgopplus - This issue happens primarily due to indexing issue with Jira. As you are using self hosted version of Jira, it becomes your companies responsibility to index your instance of Jira. Please check with your Jira Administrator to see when was Jira indexed at last. If it is long time back, then its time to re-index Jira to resolve this issue.

Such issue was raised many times so far and every time the issue was due to indexing only. So hope fully this time also same solution resolves the issue.

Other that that, just ensure that this specific Jira ticket is not having too many worklogs. When I say too many, I mean more than 1000's of worklog. If that was not the case, then most probably indexing is going to solve the issue.

**Comment by shridhar-tl** [comment]
@frgopplus - We you able to resolve this issue?

**Comment by shridhar-tl** [comment]
Hi @frgopplus - Assuming your issue is resolved, closing this ticket. Please feel free to reopen it if you are still not able to resolve it and would need additional support from me.
