### ISSUE TITLE
Worklog timer not adding small time values

### ISSUE THREAD

**Issue by talltechdude** [shridhar-tl/jira-assistant#298]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Web version

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Cloud Jira

### Version of Jira Assistant

Web

### What browser are you using?

Edge

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

MAC OS

### Bug Description

I've found an issue in the minimum worklog timer calculator for times < 1 minute and with uninitialised `TR_RoundTime` introduced in 00217589d7ce9a508d1be3e8d72443b4421b064a in `src/services/worklog-timer-service.js`. 

I'll link a PR to resolve...

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by shridhar-tl** [comment]
Hi @talltechdude, Thank you for reporting this issue and special thanks for raising a PR. Your PR has been merged and hence reported issue should have been resolved. This fix would be available for extension users as part of JA v2.49 and should be available in Web version in next couple of hours.

You can verify or use the fix from Web version just in case if you want to start using it immediately.

Closing this ticket hoping your issue is resolved.
