### ISSUE TITLE
Daywise worklog dates are always one day in arrears

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#31]
I started using the jira-assistant on Monday, 7 May 2018. I logged time all week and that time shows up in my calendar gadgets and tickewise worklog just fine. However, the daywise worklog dates are wrong.

It doesn't matter if I select an existing filter or use a custom date filter, even for just a single day, the "Logged Date" is always in arrears of the actual date.

![daywiseworklog_datesincorrect](https://user-images.githubusercontent.com/38988091/40445763-4f390630-5e8a-11e8-9145-e34bfe3bc3ff.png)

In this example, the time was logged on 7 May thru the 11 May (last week), but it is showing up as 6 May - 10 May.

![calendarviewvsdaywiseworklog_datesinccorect](https://user-images.githubusercontent.com/38988091/40445770-53d8e598-5e8a-11e8-82b1-398aca98f9e6.png)

In this example, I logged 15 minutes for today, 15 May, for a meeting. Side-by-side on the dashboard, you can see I selected 15 May in the Daywise worklog gadget. However, the logged work is showing as for 14 May.

I've confirmed that the uploaded time on the actual JIRA issue is correct.

I've also tried different date formats on the jira-assistant configuration and it doesn't make a different which format I select, it is always a day in arrears on the Daywise worklog.

**Comment by relkcaminc** [comment]
1. This is in Firefox.
2. My local timezone is US/Mountain. My JIRA profile is set to US/Mountain.
3. I don't know, I'd would assume US/Mountain as all our servers use that.

All other widgets show the correct time, so it seems it is just the Daywise worklog that has the issue.

**Comment by shridhar-tl** [comment]
Hi @relkcaminc,
If you are using chrome version of plugin then this should have been resolved in v0.50. If you are using Firefox version then still latest version is not yet published. Will publish it this week.

**Comment by relkcaminc** [comment]
Looking forward to having it resolved. Thanks for your quit attention to the issue!

**Comment by shridhar-tl** [comment]
@relkcaminc , Firefox version was published yesterday and so you should see this issue resolved now. If you still face this issue please let me know. Basically this is something related to time zones.

**Note for any one else who read this post:** It is always better to set your time zone in Jira appropriately. Because Jira will log / display your worklog based on your settings in Jira and this JiraAssist tool will take your local timezone. Most of the time issue arises when their are difference between these two. Also User Dawise worklog report has option to set different timezone for each user or group of users which enables to change the timezone accordingly.

**Comment by shridhar-tl** [comment]
Assuming this issue is resolved and closing this issue. If you are still facing any issue you can reopen this ticket.

**Comment by cmillensifer-zoll** [comment]
Please fix this - latest update has reintroduced this bug.
