### ISSUE TITLE
Unable to integrate with Outlook Calendar

### ISSUE THREAD

**Issue by irahhari** [shridhar-tl/jira-assistant#327]
### Checklist before you being

- [X] I am sure that I am already using latest version of Jira Assistant
- [X] I had verified that, no similar issues are already reported in [issue tracker](https://github.com/shridhar-tl/jira-assistant/issues)
- [X] I had tried reproducing this issue with with [Web version of Jira Assistant](https://app.jiraassistant.com) to ensure that this issue is not recently fixed and yet to be published
- [X] I had verified that, my query is not answered in [FAQ section of website](https://www.jiraassistant.com/faq)
- [X] I had verified that, my issue is not listed as [known bugs in website](https://www.jiraassistant.com/version-history)

### How do you use Jira Assistant?

Browser extension

### Are you using cloud version of Jira or self hosted (data center / server) of Jira.

Self hosted (datacenter)

### Version of Jira Assistant

v2.55

### What browser are you using?

Chrome

### What OS are you using? You need not disclose this if you feel it is irr-relevant for your issue.

Windows

### Bug Description

I tried to connect my outlook calendar to Jira Assistant extension. After checking on the check box and clicking on the link "Click here to sign in with your Microsoft account". I am getting the following website. I think that the there is issue with the redirect URL "https://jiraassistant.com/oauth/outlook"
![image](https://github.com/shridhar-tl/jira-assistant/assets/76170080/134ed901-3705-4571-94b4-0bd9400eeeaf)

PS: There is an open issue with Google calendar integration (https://github.com/shridhar-tl/jira-assistant/issues/155) (Mostly unrelated).

### Checklist before you submit

- [X] I have ensured not to paste any confidential information like Jira url, Mail id, etc.
- [X] I have verified my browser console logs and added necessary details (if required)
- [X] I have added required screenshots if the bug is related to UI (as necessary)

**Comment by irahhari** [comment]
It looks like the request is going to the Microsoft Online Server properly
![image](https://github.com/shridhar-tl/jira-assistant/assets/76170080/ac92ec9b-86c3-4dfc-9134-50b410eccd0c)

It returns the access token to the specified URL, which is permanently moved (301).
![image](https://github.com/shridhar-tl/jira-assistant/assets/76170080/a1c4afa1-c4b4-4c2a-b1ab-f3969c93a90b)

And then finally, it is not able to find the new location webpage, because of which we are getting page not found (404)
![image](https://github.com/shridhar-tl/jira-assistant/assets/76170080/de4a9172-eb54-4e59-bf04-18dceeb12a60)

As I stated earlier, it looks like a redirect URL issue. I cannot find the location of the webpages hosted on the website and this redirect URL location in the repository.

**Comment by shridhar-tl** [comment]
Hi @irahhari , This issue has been resolved and is published to Web version. It would take up to a weeks time for publishing the changes to extension users. You can once use the web version to integrate with calendar and then continue to use extension.

Using web version is simple and do not store any data outside of your browser cache similar to that of your extension.

You can know more about web version from the following url: https://app.jiraassistant.com/?authType=1

Closing this ticket considering this issue is resolved. Please feel free to reopen it or create a new ticket in case of any other issues.

**Comment by irahhari** [comment]
Thanks, @shridhar-tl. It is working now. I am able to integrate using the web version and use the extension later.

Just a few updates on the extension version. Now, suppose I try to integrate using the extension version. In that case, I am getting this "AADSTS50011: The redirect URI 'https://www.jiraassistant.com/oauth/outlook' specified in the request does not match the redirect URIs configured for the application 'a8efd8fc-0657-490e-a622-7b2aaa4f4f46'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this."

This looks like in the app you have registered with Microsoft, the redirect URL specified and the redirect URL sent with the request are different. You had mentioned that it would take weeks to fix in the extension version, which I understand, as Microsoft has to update it.

But how is it working for the web version? If the web version is also sending requests under the same application ID, then it would take weeks to fix the issue in the web version also. If the web version has a different application ID, wouldn't that also take weeks to update from Microsoft?

**Comment by shridhar-tl** [comment]
@irahhari - I think there is some mis understanding.

Currently the fix is only available in Web version. Though for extension, source code is same, for me to publish the change, it would take a week or 10 days. This is due to the fact that web store has to review the code before publish.

Hence extension still do not have latest code. So directly integrating on extension will not work until your extension gets updated to v2.56 which may take time depending on browsers.

As I had to publish the changes for individual browsers and each webstore takes its own time for review process, I cannot immediately push the changes. I had to do a round of testing with each browser and then manually publish it for each web store and then their review takes time.

You can learn more about web version here: https://jiraassistant.com/why-web-version/

**Comment by irahhari** [comment]
Thank you @shridhar-tl, for the detailed explanation and clearing the confusion.

**Comment by shridhar-tl** [comment]
@irahhari - Already v2.56 published for Chrome, Firefox and Opera. Edge is still under review and it would be published by next week. If you want to update to latest version of extension, you can do so by going to "chrome://extension", enable dev mode from top right corner and then click on update button from top left corner. That would get your extension updated to latest available version.
