### ISSUE TITLE
New Feature: Colour worklogs based on min hours instead of max hours

### ISSUE THREAD

**Issue by Alinoe22** [shridhar-tl/jira-assistant#33]
**As a** Scrum Master
**I want to**  review quickly that my team has entered their minimum aily time in JIRA
**So that** I can trust my burndown chart and other reports

-----
An option to colour the cells in red when they are **_under_** the configured time as opposed to other would be more useful to me.

**Comment by shridhar-tl** [comment]
You already have option to configure it in your settings. Set the max hours property in your Settings -> General -> worklog to your min hours and go to worklog report and click on the config icon in the top right corner of the report panel and you can see something like log less color. Set this color to red and set the hog high color to something else like green itself so that you will not notice the difference in color when it is logged high and you will see it in red when it is logged lesser than the configured hours.

It's basically how you configured the report. Please let me know if this is clear and would work for you. Sorry for late reply as I was bit busy with some other activities.

**Comment by shridhar-tl** [comment]
This requirement will be fulfilled as part of #41 using which user can build a new report like User Daywise with all the required fields and functionalities.
