### ISSUE TITLE
New Gadget: Jira-Filter

### ISSUE THREAD

**Issue by SKuettner** [shridhar-tl/jira-assistant#35]
I have to log work for issues not assigned to me (assitance, meetings). There is a Jira filter for that purpose and I'd like  to  have the option to show tickets based on such a filter (instead of adding them to the bookmark list manually). Furthermore "My open tickets" is  showing tickets of types that are used by Jira structures (package, orders ...) and I'd like to use a Jira filter instead.

**Comment by shridhar-tl** [comment]
Hi, Thank you for suggesting a feature. I will look into it and will implement it.

But for the mean time you will be able to log your work from calendar module even if the ticket is not assigned to you. You can use that module to log your work in any of the open tickets.

**Comment by shridhar-tl** [comment]
I know it is too late. But I was inactive with development from long time and become active since couple of months. If you are still in need of this, then your can just remove the "My Open Tickets" gadget from dashboard and use the custom gadget available in following link. You may need to modify the query in this custom gadget to suit your needs. Hope this helps as a replacement of My Open Tickets.

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/SHARED_REPORTS.md

**Comment by shridhar-tl** [comment]
Hi,
Your issue is resolved as part of #105. You can go to Advanced Settings page and change the JQL for appropriate instance.
