### ISSUE TITLE
Cannot Create WorkLog For Closed Tickets - But Can Enter Time Directly in JIRA

### ISSUE THREAD

**Issue by relkcaminc** [shridhar-tl/jira-assistant#37]
When adding additional time to a issue after it has been closed, an error message occurs.

![jiraassistant-cannotlogtimeonclosedticketissue](https://user-images.githubusercontent.com/38988091/40445358-2069adce-5e89-11e8-9800-c959fde32ab4.PNG)

However, work logs can still be added to the JIRA issue directly.

**Comment by shridhar-tl** [comment]
Hi @relkcaminc , I had added this validation as mostly people never add worklogs for closed tickets. But if their would be scenarios where it would be required to add worklog then I will enable it.

This ticket will be tracked as enhancements and will be implemented ASAP.

**Comment by shridhar-tl** [comment]
This issue is resolved in v0.51 and is published. An additional setting was added in Settings -> General -> Worklog tab to enable logging work for closed issues. This feature will be helpful only if Jira is configured to allow logging work for closed tickets. If not then their is no way around this.

@relkcaminc - Please check and let me know if this works for you.

**Comment by shridhar-tl** [comment]
I assume your issues is resolved and closing it. If you encounter any issue you can reopen this ticket.
