### ISSUE TITLE
Tracked time being overridden

### ISSUE THREAD

**Issue by jakul** [shridhar-tl/jira-assistant#42]
Hi,

Thanks for making this extension @shridhar-tl , it's the best way I've found to log time to JIRA. However, I have just found a bug.

I track time against tickets in multiple batches - e.g. I'll record on worklog entry of 4 hours against a ticket and then another of 1 hour. When I view the ticket in JIRA it only shows the "time spent" as being 1 hour though, not the 5 hours I expect.

Here's what Jira Assistant shows:
![captura de tela 2018-07-10 as 14 57 53 1](https://user-images.githubusercontent.com/862794/42514702-f7def4ce-8451-11e8-91ef-f891290b15b2.png)

And here's the ticket in JIRA:
![ticket_in_jira](https://user-images.githubusercontent.com/862794/42514693-f1b05688-8451-11e8-9523-851ec433c1c4.png).

**Comment by shridhar-tl** [comment]
Hi @jakul , Sorry for the delayed response. I have been bit overloaded with some work and so not able to concentrate on fixing these issues. I will try to fix this and other issues in a couple of weeks. Till then please bear with me. Thank you for being patient so far!!

**Comment by shridhar-tl** [comment]
Hi, this issue is actually with the limitations in Jira itself. Jira was not able to handle batch concurrent worklog update for same ticket. So it was not able to calculate the time properly. One such similar issue is discussed in the below link. I will have to change the worklog upload to sequential instead of concurrent upload to fix this issue. But it will obviously increase the time to upload the worklog if their are lots.

https://community.atlassian.com/t5/Jira-Software-questions/Time-Tracking-quot-Logged-quot-shows-wrong-value/qaq-p/647203

**Comment by shridhar-tl** [comment]
Hi @jakul, This issue has been resolved and is available in latest update. Please check and let me know if this issue has been resolved for you.

**Comment by jakul** [comment]
This works for me! Thanks for fixing it and keep up the good work!
