### ISSUE TITLE
JIRA Assistant not loading

### ISSUE THREAD

**Issue by AFSkier** [shridhar-tl/jira-assistant#45]
BUG: JIRA Assistant will not launch and hasn't been able to for the past 2 days.  While launching JIRA Assistant, I get a "Loading....Please Wait".

**Comment by shridhar-tl** [comment]
@AFSkier , Can you please check the console and let me know if their are any errors?

**Comment by shridhar-tl** [comment]
Hi @AFSkier, closing this issue as I haven't heard back from you from long time. If you still face any issue please reopen the ticket or create a new ticket with required details.

**Comment by AFSkier** [comment]
Chrome console errors:

[cid:image002.jpg@01D45A34.D394A380]

**Comment by AFSkier** [comment]
Chrome console errors:

[cid:image001.png@01D45A35.58858960]

**Comment by shridhar-tl** [comment]
@AFSkier - Image attachment is not available. Can you please attach it once again. Better login to Github and attach the image rather than replying through mail.

**Comment by shridhar-tl** [comment]
Console error doesn't provide all the required details. But it looks like AJAX call to your Jira server is failing due to some issue. But the error code is not properly available in console other than a 405 http error code.

To be more precise on what request is getting failed, I may need the screenshot of the network tab. You can open the network tab and refresh the page. Then check what request is getting failed and send the screenshot along with the header related details. You can click on the failed request to view the error details and send the screenshot of it. BTW, sorry for bothering you again.

Again be sure you do not expose any sensitive information while attaching the screenshot.

**Comment by AFSkier** [comment]
Chrome Console Errors (see attachment).
[Chrome_Console_Errors_JIRA_Assistant_not_loading_45_20181029.docx](https://github.com/shridhar-tl/jira-assistant/files/2526469/Chrome_Console_Errors_JIRA_Assistant_not_loading_45_20181029.docx)
