### ISSUE TITLE
Allow Logged Work - [User - Day wise] to be added to the dashboard

### ISSUE THREAD

**Issue by eladbz** [shridhar-tl/jira-assistant#46]
Great report should be able to put it with the same users and time frame (e.g last week) to the dashboard

**Comment by shridhar-tl** [comment]
This will be implemented ASAP. Just to let you know, this would be also possible based on implementation of #41.

**Comment by eladbz** [comment]
Thank you

**Comment by shridhar-tl** [comment]
@eladbz or anyone else can you let me know what value do you think it adds?

As of now, instead of looking at Dashboard, you can look at Worklog report and you get to see the same data. Moreover for worklog report, having lots of space is really necessary. If it is added as a small gadget, user's won't be able to see the data without scrolling and that too won't give good overview. So I am not sure if it would be really useful.

I am closing this ticket for now as won't fix. Please outline your use case if you really feel it helps you and reopen the ticket. I am happy to have it implemented in next release if it really adds some value.
