### ISSUE TITLE
My open tickets: show tickets where i am "implementer" too

### ISSUE THREAD

**Issue by drozel** [shridhar-tl/jira-assistant#50]
Currently widget "My open tickets" shows only tickets assigned to current user with "assignee" field.
It could be nice to be able to change this filter or just to show all tickets referencing to this user with other fields, like "implementer" etc.

**Comment by shridhar-tl** [comment]
Hi,
You could use Custom report to generate such gadget and add it to dashboard. Hope that would give you what is needed.

**Comment by drozel** [comment]
Hi, thank you,
i`ve tried it, but the "save query" button below is inactive.
Is it a Jira functionality, which shall be enabled or something in Jira Assistant?

**Comment by drozel** [comment]
![image](https://user-images.githubusercontent.com/6229397/45027491-d3f1c480-b041-11e8-9956-9720d7f0674e.png)
Hi, it does not work without any errors in console...

**Comment by shridhar-tl** [comment]
Hi, I know it is too late to reply. But I was inactive with development from long time and become active since couple of months. If you are still in need of a solution, then your can just remove the "My Open Tickets" gadget from dashboard and use the custom gadget available in following link. You may need to modify the query in this custom gadget to suit your needs. Hope this helps.

https://github.com/shridhar-tl/jira-assistant/blob/master/docs/SHARED_REPORTS.md

**Comment by shridhar-tl** [comment]
Hi @drozel,
As part of #105, you initial request to change the JQL for My Open Tickets is now possible through Advanced Settings page. Also I hope the issue you reported in Custom Reports should also have got resolved as whole new version of Jira Assistant is published.

Hence closing this issue. If you face any other issue please feel free to reopen it.
