### ISSUE TITLE
Feature Request: Re-order users in user-groups or sort by alphabetical order

### ISSUE THREAD

**Issue by Shiyazudeen** [shridhar-tl/jira-assistant#91]
It would be very useful if there is an ability to either re-order the users in an existing group, or even sort the names by alphabetical order. Currently, names get added at the end. This creates an issue while adding or removing team members. Thanks for the great work team JA.

**Comment by shridhar-tl** [comment]
This change has been implemented and is available since Jira Assistant v0.77 for Chrome.

**Note:** Existing data will not be sorted automatically. When you try to add new user it will get sorted. So if you would like the existing users list to be sorted, then as a workaround, do add a new user to the list and the list will get sorted immediately.

**Comment by shridhar-tl** [comment]
Hi @Shiyazudeen - FYI. Please read my comment above and let me know if you still face any issues.

**Comment by Shiyazudeen** [comment]
Thank you @shridhar-tl this works perfectly well now. Am on Firefox and it works great there too.
