### ISSUE TITLE
WorkLog report to not display non working days

### ISSUE THREAD

**Issue by riteshmuhatte** [shridhar-tl/jira-assistant#95]
based on the working days, Worklog Report should only display working days and not show weekly off days

**Comment by shridhar-tl** [comment]
Hi @riteshmuhatte - Are you still using Jira Assistant? If yes, I am happy to let you know that your request to hide non working days has been implemented in New worklog report and is configurable. It is already available in Web version and for extension users it would be published in next couple of weeks.

I'm closing this issue considering your issue is resolved. Please feel free to reopen it if you have any issues with it.
