### ISSUE TITLE
no vertical scrolling in calendar/worklogs

### ISSUE THREAD

**Issue by rburdick-lotlinx** [shridhar-tl/jira-assistant#97]
my work day never fits on screen, so i've always scrolled up/down to view it, but today there's no scrollbars and no scrolling happening - even on weeks where i have existing work logged i can't scroll down to view it all. this is in the beta, which i've been using without issue for weeks. attempting to switch back to the old version is even worse - just an empty grey pane where i'd expect to see the calendar and worklogs

**Comment by shridhar-tl** [comment]
@rburdick-lotlinx  - Thank you for reporting this issue. This issue has been resolved and is available since v0.83 of Jira Assistant. It is already published but it would take around an hour to be available in webstore. Once your version gets updated, this issue would get resolved. You can also manually update your version once v0.83 is available in Web Store.

**Comment by rburdick-lotlinx** [comment]
looks great now, thanks!
